gaussianBlur:
  kernelSize: 3
  sigmaX: 20
  sigmaY: 0
clahe:
  clipLimit: 3
  tileGridSize: 2
hysteresis:
  lowerThresh: 150
  highThresh: 200
contours:
  approxPolyDPEpsilon: 0.02
filter:
  slopeThresh: 0.30
card:
  width: 500
  height: 726
  cornerWidth: 100
  cornerHeight: 190